<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>CobrasAmmoStack</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>Library</OutputType>

		<Version>1.1.0</Version>
		<AssemblyVersion>1.1.0.0</AssemblyVersion>
		<FileVersion>1.1.0.0</FileVersion>
		<InformationalVersion>1.1.0</InformationalVersion>

		<OutputPath>bin\$(Configuration)\$(ProjectName)\$(AssemblyName)\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SPTarkov.Common" Version="4.1.1" />
		<PackageReference Include="SPTarkov.DI" Version="4.1.1" />
		<PackageReference Include="SPTarkov.Server.Core" Version="4.1.1" />
	</ItemGroup>
	<ItemGroup>
		<None Update="config.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>